(relation dessert ())
(relation cone ())
(relation blizzard (i64 i64))
(relation blizzard_machine ())
(relation ice_cream (i64))
(relation topping (i64))
(relation ice ())
(relation milk (i64))

(rule () ((ice_cream 1)))
(rule () ((ice_cream 2)))
(rule () ((ice_cream 3)))
(rule () ((ice_cream 4)))
(rule () ((topping 1)))
(rule () ((topping 2)))
(rule () ((topping 3)))
(rule () ((topping 4)))
(rule () ((milk 1)))
(rule () ((milk 2)))
(rule () ((milk 3)))
(rule () ((milk 4)))
(rule ((ice) (milk i64)) ((ice_cream i64)))
(rule ((ice_cream x) (blizzard_machine) (topping y)) ((blizzard x y)))
(rule ((ice_cream i64)) ((cone)))
(rule ((cone)) ((dessert)))
(rule ((blizzard x y)) ((dessert)))

(run 100)

(check (dessert))
